//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Objects/Player/ControlSchemes/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""75bdfe1f-ab33-48af-b295-e156f3f1bdc6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3887e31d-97d0-483a-ac55-6103b075ce31"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""89bdae6d-0acc-48f9-afb1-3535bc86a9d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""79848dbd-2006-457d-81be-d691dca4cc23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""98834595-9d46-43f1-accf-19b7ca28f835"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerMenu"",
                    ""type"": ""Button"",
                    ""id"": ""77580832-492a-471c-9a71-0629d2696b00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""03df96b1-fb29-4aed-ab61-85b3b4163e64"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9297176a-06aa-4efa-af7d-11aa8003b8bd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""77e10524-299d-4a9a-b39e-eb52ecfb84f4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9829eac7-b45f-4f9c-817b-a30d41e4d726"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f8e3e9de-661e-4496-ba96-81e1afdef6fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""57962e03-dc3a-47ec-a5a2-7cf84ff09f6a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3aad9e46-6980-43b6-8988-59971c42e486"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""140fdda7-da2e-43f9-9db2-a21b7b69fd5d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d2591a7-ee9d-4f9f-9e8e-1a4bf6cfc7c7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""f458d322-c646-44e8-bd7e-93d7acbbc27d"",
            ""actions"": [
                {
                    ""name"": ""Inventory-RotateItem"",
                    ""type"": ""Value"",
                    ""id"": ""caefa83e-c086-4a9f-aa01-367fba281c9b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hotbar-SelectSlot"",
                    ""type"": ""Value"",
                    ""id"": ""fec27dd5-eeba-4e9b-bbaa-86da3f9db564"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hotbar-SelectByKey"",
                    ""type"": ""Button"",
                    ""id"": ""e659900e-92cb-4398-b03b-dfaa3385e60f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Scrollwheel"",
                    ""id"": ""23e16684-6a8c-4b18-8074-e6489e984220"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""ae33bb14-01f7-41e1-951b-66a752279fe7"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""0000e51e-b0fa-43f8-801e-b1be62e11a40"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""7b9c875c-eef2-4bc4-942b-0cf46fb08564"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8ac1dc87-13f8-4816-bb0d-bb30cf533fd8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5fde5ac7-c664-42b9-987d-2c371e040eda"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory-RotateItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Scrollwheel"",
                    ""id"": ""a8476ec3-8402-4483-b5b5-cdb5ad7d30c3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""78e28fb4-e88d-4e68-acee-142f2029d15b"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""95893757-8782-42e2-84e8-32b8ad0681ef"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""53ba7d3a-e37d-465c-8a4f-ee72296d1559"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a2fc2081-83f4-4d08-84a6-3eafc8c73ece"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""40d7573e-89b2-43e8-b53f-6660565c531e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f18aa240-73bb-4ccd-a1bd-5f2903001a7a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5457bf0c-243f-4719-b8e2-02689bdcfaf2"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a078b75-908a-4e4c-9f07-677faf3483dd"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75a22b7c-928c-4f51-acfc-1fe79fbc5dda"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e07f76f0-a931-4fe6-bffd-06cf7be5383e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a87db45-8a48-4e5b-a777-63dc4a44626d"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea1a192e-2d2e-45e4-b5da-e874b30a0207"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf1f8c9e-3ec5-4042-a0f4-61f5e0625061"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ecba87-f01e-45c4-9188-45f290d0af2a"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7617bcb9-bb70-4386-94c3-d19eecd5d2a9"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar-SelectByKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Service"",
            ""id"": ""e79682f7-f1b4-4f58-ace5-25cf4b93a824"",
            ""actions"": [
                {
                    ""name"": ""ScrollOrderTag"",
                    ""type"": ""Value"",
                    ""id"": ""de468845-9bfb-49df-8a10-92a8e0937a10"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Scrollwheel"",
                    ""id"": ""d2e41cec-da77-4c7f-bb41-758c07c38438"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""4d5fc645-eda0-4d35-b014-f57c4efbdbbc"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""f36703b1-89f9-4f19-b9ad-97471b8ad4e4"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""b067e1b8-b4e8-432d-b09b-5af0d86f2d01"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""be7843cf-f78e-4dff-9089-d082ee47dacd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c86d2400-4ce4-4b5f-8a28-03c17fb97161"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrderTag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Move = m_General.FindAction("Move", throwIfNotFound: true);
        m_General_Sprint = m_General.FindAction("Sprint", throwIfNotFound: true);
        m_General_Interact = m_General.FindAction("Interact", throwIfNotFound: true);
        m_General_Pause = m_General.FindAction("Pause", throwIfNotFound: true);
        m_General_PlayerMenu = m_General.FindAction("PlayerMenu", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_InventoryRotateItem = m_Menu.FindAction("Inventory-RotateItem", throwIfNotFound: true);
        m_Menu_HotbarSelectSlot = m_Menu.FindAction("Hotbar-SelectSlot", throwIfNotFound: true);
        m_Menu_HotbarSelectByKey = m_Menu.FindAction("Hotbar-SelectByKey", throwIfNotFound: true);
        // Service
        m_Service = asset.FindActionMap("Service", throwIfNotFound: true);
        m_Service_ScrollOrderTag = m_Service.FindAction("ScrollOrderTag", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private List<IGeneralActions> m_GeneralActionsCallbackInterfaces = new List<IGeneralActions>();
    private readonly InputAction m_General_Move;
    private readonly InputAction m_General_Sprint;
    private readonly InputAction m_General_Interact;
    private readonly InputAction m_General_Pause;
    private readonly InputAction m_General_PlayerMenu;
    public struct GeneralActions
    {
        private @PlayerControls m_Wrapper;
        public GeneralActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_General_Move;
        public InputAction @Sprint => m_Wrapper.m_General_Sprint;
        public InputAction @Interact => m_Wrapper.m_General_Interact;
        public InputAction @Pause => m_Wrapper.m_General_Pause;
        public InputAction @PlayerMenu => m_Wrapper.m_General_PlayerMenu;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void AddCallbacks(IGeneralActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @PlayerMenu.started += instance.OnPlayerMenu;
            @PlayerMenu.performed += instance.OnPlayerMenu;
            @PlayerMenu.canceled += instance.OnPlayerMenu;
        }

        private void UnregisterCallbacks(IGeneralActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @PlayerMenu.started -= instance.OnPlayerMenu;
            @PlayerMenu.performed -= instance.OnPlayerMenu;
            @PlayerMenu.canceled -= instance.OnPlayerMenu;
        }

        public void RemoveCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGeneralActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GeneralActions @General => new GeneralActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_InventoryRotateItem;
    private readonly InputAction m_Menu_HotbarSelectSlot;
    private readonly InputAction m_Menu_HotbarSelectByKey;
    public struct MenuActions
    {
        private @PlayerControls m_Wrapper;
        public MenuActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @InventoryRotateItem => m_Wrapper.m_Menu_InventoryRotateItem;
        public InputAction @HotbarSelectSlot => m_Wrapper.m_Menu_HotbarSelectSlot;
        public InputAction @HotbarSelectByKey => m_Wrapper.m_Menu_HotbarSelectByKey;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @InventoryRotateItem.started += instance.OnInventoryRotateItem;
            @InventoryRotateItem.performed += instance.OnInventoryRotateItem;
            @InventoryRotateItem.canceled += instance.OnInventoryRotateItem;
            @HotbarSelectSlot.started += instance.OnHotbarSelectSlot;
            @HotbarSelectSlot.performed += instance.OnHotbarSelectSlot;
            @HotbarSelectSlot.canceled += instance.OnHotbarSelectSlot;
            @HotbarSelectByKey.started += instance.OnHotbarSelectByKey;
            @HotbarSelectByKey.performed += instance.OnHotbarSelectByKey;
            @HotbarSelectByKey.canceled += instance.OnHotbarSelectByKey;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @InventoryRotateItem.started -= instance.OnInventoryRotateItem;
            @InventoryRotateItem.performed -= instance.OnInventoryRotateItem;
            @InventoryRotateItem.canceled -= instance.OnInventoryRotateItem;
            @HotbarSelectSlot.started -= instance.OnHotbarSelectSlot;
            @HotbarSelectSlot.performed -= instance.OnHotbarSelectSlot;
            @HotbarSelectSlot.canceled -= instance.OnHotbarSelectSlot;
            @HotbarSelectByKey.started -= instance.OnHotbarSelectByKey;
            @HotbarSelectByKey.performed -= instance.OnHotbarSelectByKey;
            @HotbarSelectByKey.canceled -= instance.OnHotbarSelectByKey;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // Service
    private readonly InputActionMap m_Service;
    private List<IServiceActions> m_ServiceActionsCallbackInterfaces = new List<IServiceActions>();
    private readonly InputAction m_Service_ScrollOrderTag;
    public struct ServiceActions
    {
        private @PlayerControls m_Wrapper;
        public ServiceActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScrollOrderTag => m_Wrapper.m_Service_ScrollOrderTag;
        public InputActionMap Get() { return m_Wrapper.m_Service; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ServiceActions set) { return set.Get(); }
        public void AddCallbacks(IServiceActions instance)
        {
            if (instance == null || m_Wrapper.m_ServiceActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ServiceActionsCallbackInterfaces.Add(instance);
            @ScrollOrderTag.started += instance.OnScrollOrderTag;
            @ScrollOrderTag.performed += instance.OnScrollOrderTag;
            @ScrollOrderTag.canceled += instance.OnScrollOrderTag;
        }

        private void UnregisterCallbacks(IServiceActions instance)
        {
            @ScrollOrderTag.started -= instance.OnScrollOrderTag;
            @ScrollOrderTag.performed -= instance.OnScrollOrderTag;
            @ScrollOrderTag.canceled -= instance.OnScrollOrderTag;
        }

        public void RemoveCallbacks(IServiceActions instance)
        {
            if (m_Wrapper.m_ServiceActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IServiceActions instance)
        {
            foreach (var item in m_Wrapper.m_ServiceActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ServiceActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ServiceActions @Service => new ServiceActions(this);
    public interface IGeneralActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnPlayerMenu(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnInventoryRotateItem(InputAction.CallbackContext context);
        void OnHotbarSelectSlot(InputAction.CallbackContext context);
        void OnHotbarSelectByKey(InputAction.CallbackContext context);
    }
    public interface IServiceActions
    {
        void OnScrollOrderTag(InputAction.CallbackContext context);
    }
}
